#!/usr/bin/env python


import sys
import re
import numpy as np
from matplotlib import pyplot


num_entries = 0
min_val = 0
max_val = 0

# extract '#define's from lut.h
with open('lut.h') as f:
    for line in f:
        m = re.search('#define\sLUT_NUM_ENTRIES\s([0-9]*)', line)
        if m is not None:
            if m.group(1) is not None:
                num_entries = int(m.group(1))
                break
with open('lut.h') as f:
    for line in f:
        m = re.search('#define\sLUT_MIN_VAL\s([0-9]*)', line)
        if m is not None:
            if m.group(1) is not None:
                min_val = int(m.group(1))
                break
with open('lut.h') as f:
    for line in f:
        m = re.search('#define\sLUT_MAX_VAL\s([0-9]*)', line)
        if m is not None:
            if m.group(1) is not None:
                max_val = int(m.group(1))
                break

# generate entries
seg120 = 2*np.pi/3
phase = np.linspace(0, 2*np.pi, num=num_entries, endpoint=False);

a = np.sin(phase           )
b = np.sin(phase + 1*seg120)
c = np.sin(phase + 2*seg120)

a += 1
b += 1
c += 1

a *= (max_val-min_val)/2
b *= (max_val-min_val)/2
c *= (max_val-min_val)/2

a += min_val
b += min_val
c += min_val

a[a < min_val] = min_val
b[b < min_val] = min_val
c[c < min_val] = min_val

a[a > max_val] = max_val
b[b > max_val] = max_val
c[c > max_val] = max_val

# convert to integer
a = a.astype(int)
b = b.astype(int)
c = c.astype(int)

# write to plot
pyplot.plot(phase, a, phase, b, phase, c, linestyle='steps')
pyplot.savefig('lut_data.png', bbox_inches='tight')

# write to lut_data.c
with open('lut_data.c', 'w') as f:
    f.write('/////////////////////////////////////////\n')
    f.write('//// - autogenerated by {} - ////\n'.format(sys.argv[0]))
    f.write('/////////////////////////////////////////\n')
    f.write('\n')
    f.write('#include "lut.h"\n')
    f.write('\n')
    f.write('uint8_t lut[][3] = {\n')
    for [aa, bb, cc] in zip(a, b, c):
        f.write('\t{{ 0x{:02X}, 0x{:02X}, 0x{:02X} }},\n'.format(aa, bb, cc))
    f.write('};\n')
